# requires to run this commmand `$ gcloud compute disks create --size=5GB --zone=us-east1-b gce-nfs-disk`
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gce-nfs-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  labels:
    app: wp01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
